<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<Content Include="Permissions\grant-applicationWriteDb-permissions.sql">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup> 
	
	<ItemGroup> 
		<PackageReference Include="BeCause.NuGet.EntryPoint.DatabaseMigration" Version="3.1.0" />
		<PackageReference Include="BeCause.NuGet.DatabaseMigration" Version="3.1.0" />
		<PackageReference Include="BeCause.NuGet.Telemetry" Version="3.1.0" />
	</ItemGroup>
	
	<ItemGroup>
		<None Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup> 
	<ItemGroup>
		<None Update="Permissions\*.sql">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
