<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>HealthTracker.SharedDomain</RootNamespace>
		<AssemblyName>HealthTracker.SharedDomain</AssemblyName>
		<IsPackable>true</IsPackable>
		<IsPublishable>true</IsPublishable>
		<IsTestProject>false</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BeCause.NuGet.Core.Domain" Version="3.1.0" />
	</ItemGroup>
</Project>
